const mongoose = require('mongoose');
const Plant = require('./plant_model');

const mongoDbUrl =
  'mongodb+srv://Anthony-O:CC8txqzZ16v2lcra@cluster0.61xuyqe.mongodb.net/seedling';

const connectToMongoDb = (dbUrl) => {
  mongoose
    .connect(dbUrl, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    })
    .then(() => console.log(`Successfully connected to MongoDB (${dbUrl})`))
    .catch((error) => {
      throw new Error(`Something went wrong (${error.message})`);
    });
};

const seedDB = async (model, data) => {
  await model.deleteMany({});
  await model.insertMany(data);
};

const plants = [
  {
    Categories: 'Dracaena',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5556.jpg',
    Use: ['Potted plant', 'Secondary'],
    'Latin name': "Dracaena deremensis 'Janet Craig'",
    Insects: ['Mealy bug', 'Scale'],
    Avaibility: 'Regular',
    Style: 'Bush',
    Bearing: 'Erect',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.91,
      CM: 91,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.91,
      CM: 91,
    },
    id: '53417c12-4824-5995-bce0-b81984ebbd1d',
    Appeal: 'Robustness',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 1.22,
      CM: 122,
    },
    'Common name (fr.)': 'Janet Craig',
    Pruning: 'If needed',
    Family: 'Liliaceae',
    'Height potential': {
      M: 3.66,
      CM: 366,
    },
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 86,
      C: 30,
    },
    'Blooming season': 'Winter / Spring',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-121.html',
    'Color of leaf': ['Dark green'],
    Watering: 'Keep moist between watering & Can dry between watering',
    'Color of blooms': 'Light green',
    Zone: ['11-10'],
    'Common name': ['Janet Craig'],
    'Available sizes (Pot)': '4in to 14in / 10cm to 36cm',
    'Other names': null,
    'Temperature min': {
      F: 50,
      C: 10,
    },
    'Pot diameter (cm)': {
      M: 0.25,
      CM: 25,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Palm',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5725.jpg',
    Use: ['Potted plant', 'Secondary'],
    'Latin name': 'Rhapis excelsa',
    Insects: ['N/A'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.91,
      CM: 91,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.71,
      CM: 71,
    },
    id: '9b97aef1-20a4-5620-af90-7d64dadb414e',
    Appeal: 'Foliage',
    Perfume: null,
    Growth: 'Slow',
    'Width potential': {
      M: 3.05,
      CM: 305,
    },
    'Common name (fr.)': null,
    Pruning: 'Never',
    Family: 'Arecaceae',
    'Height potential': {
      M: 3.66,
      CM: 366,
    },
    Origin: ['China'],
    Description: null,
    'Temperature max': {
      F: 86,
      C: 30,
    },
    'Blooming season': null,
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-290.html',
    'Color of leaf': ['Dark green'],
    Watering: 'Keep moist between watering & Must not dry between watering',
    'Color of blooms': null,
    Zone: ['11', '9'],
    'Common name': ['Lady palm'],
    'Available sizes (Pot)': '6in to 32in / 15cm to 81cm',
    'Other names': 'Rhapis flabelliformis',
    'Temperature min': {
      F: 46.4,
      C: 8,
    },
    'Pot diameter (cm)': {
      M: 0.25,
      CM: 25,
    },
    Climat: 'Subtropical',
  },
  {
    Categories: 'Anthurium',
    Disease: 'Erwinia & Crown rot',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5491.jpg',
    Use: ['Flower', 'Table top', 'Tertiary'],
    'Latin name': 'Anthurium X',
    Insects: ['Spider mite', 'Mealy bug', 'Aphid'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.25,
      CM: 25,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.3,
      CM: 30,
    },
    id: '215b33f4-66d2-5601-b776-4501f2bd50b7',
    Appeal: 'Flower',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 0.61,
      CM: 61,
    },
    'Common name (fr.)': 'Flamant rose, Langue de feu',
    Pruning: 'Never',
    Family: 'Araceae',
    'Height potential': {
      M: 0.61,
      CM: 61,
    },
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 71.6,
      C: 22,
    },
    'Blooming season': 'All year',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-56.html',
    'Color of leaf': ['Medium green', 'Dark green'],
    Watering: 'Water when soil is half dry & Can dry between watering',
    'Color of blooms': 'Pink',
    Zone: ['11'],
    'Common name': ['Tailflower', 'Wax flower'],
    'Available sizes (Pot)': '3in to 14in / 8cm to 36cm',
    'Other names': null,
    'Temperature min': {
      F: 64.4,
      C: 18,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Other',
    Disease: 'Phytophtora & Crown rot',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5486.jpg',
    Use: ['Colors / Forms', 'Table top', 'Tertiary'],
    'Latin name': 'Alocasia X amazonica',
    Insects: ['Spider mite', 'Mealy bug'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.3,
      CM: 30,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.3,
      CM: 30,
    },
    id: '55a0e4fa-0717-521d-9671-0fc9095f2055',
    Appeal: 'Foliage',
    Perfume: null,
    Growth: 'Slow',
    'Width potential': {
      M: 0.91,
      CM: 91,
    },
    'Common name (fr.)': "Oreille d'lphant",
    Pruning: 'Never',
    Family: 'Araceae',
    'Height potential': {
      M: 1.52,
      CM: 152,
    },
    Origin: ['Hybrid'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'Seasonal',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-51.html',
    'Color of leaf': ['Dark green', 'Grey'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Light green',
    Zone: ['11'],
    'Common name': ['Elephant ear'],
    'Available sizes (Pot)': '4in to 14in / 10cm to 36cm',
    'Other names': '(A. sanderiana x A. lowii grandis)',
    'Temperature min': {
      F: 59,
      C: 15,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical humid',
  },
  {
    Categories: 'Dracaena',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5586.jpg',
    Use: ['Potted plant', 'Primary'],
    'Latin name': "Dracaena reflexa 'Song of Jamaica'",
    Insects: ['Mealy bug'],
    Avaibility: 'Regular',
    Style: 'Multi',
    Bearing: 'Arborescent',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 1.68,
      CM: 168,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.91,
      CM: 91,
    },
    id: '99596292-0712-5d51-8b94-669d621c504a',
    Appeal: 'Bearing',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 3.05,
      CM: 305,
    },
    'Common name (fr.)': 'Dracaena de Malaisie',
    Pruning: 'If needed',
    Family: 'Liliaceae',
    'Height potential': {
      M: 6.1,
      CM: 610,
    },
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 86,
      C: 30,
    },
    'Blooming season': 'Winter',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-151.html',
    'Color of leaf': ['Dark green', 'Yellow'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Medium green',
    Zone: ['11-10'],
    'Common name': ['Malaysian Dracaena'],
    'Available sizes (Pot)': '6in to 48in / 15cm to 122cm',
    'Other names': 'Pleomele reflexa',
    'Temperature min': {
      F: 53.6,
      C: 12,
    },
    'Pot diameter (cm)': {
      M: 0.36,
      CM: 36,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Aglaonema',
    Disease: 'Phytophtora , Crown rot',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5466.jpg',
    Use: ['Table top', 'Ground cover', 'Tertiary'],
    'Latin name': "Aglaonema 'Jubilee'",
    Insects: ['Mealy bug', 'Scale'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.3,
      CM: 30,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.3,
      CM: 30,
    },
    id: '894d8453-28a0-59d1-ac0a-132dff7ee7a5',
    Appeal: 'Foliage',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 0.91,
      CM: 91,
    },
    'Common name (fr.)': 'Aglaonema',
    Pruning: 'If needed',
    Family: 'Araceae',
    'Height potential': {
      M: 0.91,
      CM: 91,
    },
    Origin: ['Hybrid'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'Seasonal',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-31.html',
    'Color of leaf': ['Dark green', 'Grey'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Light green',
    Zone: ['11'],
    'Common name': ['Chinese Evergreen'],
    'Available sizes (Pot)': '6in to 14in / 15cm to 36cm',
    'Other names': null,
    'Temperature min': {
      F: 64.4,
      C: 18,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Dracaena',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5585.jpg',
    Use: ['Potted plant', 'Primary'],
    'Latin name': "Dracaena reflexa 'Song of Jamaica'",
    Insects: ['Mealy bug'],
    Avaibility: 'Regular',
    Style: 'Bush',
    Bearing: 'Arborescent',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 1.22,
      CM: 122,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.91,
      CM: 91,
    },
    id: 'e5be9fde-3069-552c-969c-bb59f0fab9f2',
    Appeal: 'Bearing',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 3.05,
      CM: 305,
    },
    'Common name (fr.)': 'Dracaena de Malaisie',
    Pruning: 'If needed',
    Family: 'Liliaceae',
    'Height potential': {
      M: 6.1,
      CM: 610,
    },
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 86,
      C: 30,
    },
    'Blooming season': 'Winter',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-150.html',
    'Color of leaf': ['Dark green', 'Yellow'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Medium green',
    Zone: ['11-10'],
    'Common name': ['Malaysian Dracaena'],
    'Available sizes (Pot)': '6in to 48in / 15cm to 122cm',
    'Other names': 'Pleomele reflexa',
    'Temperature min': {
      F: 53.6,
      C: 12,
    },
    'Pot diameter (cm)': {
      M: 0.36,
      CM: 36,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Hanging',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5657.jpg',
    Use: ['Hanging', 'Table top'],
    'Latin name': 'Maranta leuconeura erythroneura',
    Insects: ['Mealy bug'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Creeping',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.25,
      CM: 25,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.51,
      CM: 51,
    },
    id: 'f66ad303-c2ff-55ac-8689-036553b740fe',
    Appeal: 'Color',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': null,
    'Common name (fr.)': 'Plante religieuse, Plante qui prie, Plante prieuse',
    Pruning: 'If needed',
    Family: 'Marantaceae',
    'Height potential': {
      M: 0.25,
      CM: 25,
    },
    Origin: ['Brazil'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'Spring',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-222.html',
    'Color of leaf': ['Medium green', 'Red'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Lilac & White',
    Zone: ['11-10'],
    'Common name': ['Herringbone', 'Pink praying plant'],
    'Available sizes (Pot)': '4in to 10in / 10cm to 25cm',
    'Other names': null,
    'Temperature min': {
      F: 53.6,
      C: 12,
    },
    'Pot diameter (cm)': {
      M: 0.2,
      CM: 20,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Bromeliad',
    Disease: 'N/A',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5632.jpg',
    Use: ['Table top', 'Tertiary'],
    'Latin name': "Guzmenia 'Marjan'",
    Insects: ['N/A'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Rosette',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.46,
      CM: 46,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.46,
      CM: 46,
    },
    id: '3d205401-ce59-5ca4-8e0d-3c122c207fc0',
    Appeal: 'Flower',
    Perfume: null,
    Growth: 'Slow',
    'Width potential': null,
    'Common name (fr.)': 'Guzmania',
    Pruning: 'Never',
    Family: 'Bromeliaceae',
    'Height potential': null,
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 86,
      C: 30,
    },
    'Blooming season': 'Seasonal',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-197.html',
    'Color of leaf': ['Medium green'],
    Watering: 'Water when soil is half dry & Change water regularly in the cup',
    'Color of blooms': 'Yellow & Red',
    Zone: ['11-10'],
    'Common name': ['Guzmania'],
    'Available sizes (Pot)': '4in to 6in / 10cm to 15cm',
    'Other names': null,
    'Temperature min': {
      F: 50,
      C: 10,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Aglaonema',
    Disease: 'Phytophtora , Crown rot',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5480.jpg',
    Use: ['Table top', 'Ground cover', 'Tertiary'],
    'Latin name': "Aglaonema 'Silver Queen'",
    Insects: ['Mealy bug', 'Scale'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.25,
      CM: 25,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.3,
      CM: 30,
    },
    id: 'f08f56e9-1122-5268-92d3-f36825fb3168',
    Appeal: 'Foliage',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 0.76,
      CM: 76,
    },
    'Common name (fr.)': 'Aglaonema',
    Pruning: 'If needed',
    Family: 'Araceae',
    'Height potential': {
      M: 0.76,
      CM: 76,
    },
    Origin: ['Hybrid'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'Seasonal',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-45.html',
    'Color of leaf': ['Grey', 'Medium green'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Light green',
    Zone: ['11'],
    'Common name': ['Chinese Evergreen'],
    'Available sizes (Pot)': '6in to 14in / 15cm to 36cm',
    'Other names': null,
    'Temperature min': {
      F: 64.4,
      C: 18,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Spathiphyllum',
    Disease: 'Phytophtora',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5758.jpg',
    Use: ['Table top', 'Tertiary'],
    'Latin name': "Spathiphyllum 'Ceres'",
    Insects: ['Mealy bug', 'Thrips'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 0.3,
      CM: 30,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 0.3,
      CM: 30,
    },
    id: 'f9f9bc5a-d562-5c55-a027-819eb64eee91',
    Appeal: 'Flower',
    Perfume: 'Light, comes from the Flowers',
    Growth: 'Regular',
    'Width potential': {
      M: 0.91,
      CM: 91,
    },
    'Common name (fr.)': 'Lys de paix',
    Pruning: 'Never',
    Family: 'Araceae',
    'Height potential': {
      M: 0.91,
      CM: 91,
    },
    Origin: ['Cultivar'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'All year',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-323.html',
    'Color of leaf': ['Dark green'],
    Watering: 'Keep moist between watering & Must not dry between watering',
    'Color of blooms': 'White',
    Zone: ['11-10'],
    'Common name': ['Peace lily'],
    'Available sizes (Pot)': '4in to 10in / 10cm to 25cm',
    'Other names': null,
    'Temperature min': {
      F: 59,
      C: 15,
    },
    'Pot diameter (cm)': {
      M: 0.15,
      CM: 15,
    },
    Climat: 'Tropical',
  },
  {
    Categories: 'Aglaonema',
    Disease: 'Phytophtora , Crown rot',
    Img: 'http://www.tropicopia.com/house-plant/thumbnails/5477.jpg',
    Use: ['Potted plant', 'Primary', 'Secondary'],
    'Latin name': "Aglaonema 'Queen of Siam'",
    Insects: ['Mealy bug', 'Scale'],
    Avaibility: 'Regular',
    Style: null,
    Bearing: 'Clump',
    'Light tolered': 'Diffuse light ( Less than 5,300 lux / 500 fc)',
    'Height at purchase': {
      M: 1.02,
      CM: 102,
    },
    'Light ideal': 'Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)',
    'Width at purchase': {
      M: 1.07,
      CM: 107,
    },
    id: 'e86d1a7a-af49-5b71-84a6-38f08df1ac54',
    Appeal: 'Foliage',
    Perfume: null,
    Growth: 'Regular',
    'Width potential': {
      M: 1.22,
      CM: 122,
    },
    'Common name (fr.)': 'Aglaonema',
    Pruning: 'If needed',
    Family: 'Araceae',
    'Height potential': {
      M: 1.22,
      CM: 122,
    },
    Origin: ['Hybrid'],
    Description: null,
    'Temperature max': {
      F: 82.4,
      C: 28,
    },
    'Blooming season': 'Seasonal',
    Url: 'http://www.tropicopia.com/house-plant/detail.np/detail-42.html',
    'Color of leaf': ['Medium green', 'White'],
    Watering: 'Keep moist between watering & Water when soil is half dry',
    'Color of blooms': 'Light green',
    Zone: ['11'],
    'Common name': ['Chinese Evergreen'],
    'Available sizes (Pot)': '8in to 14in / 20cm to 36cm',
    'Other names': null,
    'Temperature min': {
      F: 64.4,
      C: 18,
    },
    'Pot diameter (cm)': {
      M: 0.36,
      CM: 36,
    },
    Climat: 'Tropical',
  },
];

connectToMongoDb(mongoDbUrl);

seedDB(Plant, plants).then(() => {
  console.log('Database seeded!');
  mongoose.connection.close();
});
